export enum MaxPrice {
    Free = 'free',
    Five = '5',
    Ten = '10',
    Fifteen = '15',
    Twenty = '20',
    TwentyFive = '25',
    Thirty = '30',
    ThirtyFive = '35',
    Forty = '40',
    FortyFive = '45',
    Fifty = '50',
    FiftyFive = '55',
    Sixty = '60',
    All = '',
}